automation:
  - id: "car_heater_on_timer"
    alias: "CH: Turn on car heating timer"
    trigger:
      - entity_id: input_boolean.car_heater_enable
        from: "off"
        platform: state
        to: "on"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.car_heater_3h_before_temp
          # CHANGE-ME: outside temperature sensor : DONE
          value: "{{ states('sensor.out_temperature') | float }}"
      - event: car_heater_timer_enabled

    #------------automation

  - id: "car_heater_start_if_needed"
    alias: "CH: Turn on car heating immediately if needed"
    trigger:
      - platform: event
        event_type: car_heater_timer_enabled
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states.sensor.car_time_until_departure.state|float > 0 }}"
        - condition: template
          value_template: "{{ (states.sensor.car_heater_run_time.state|float * 60) >= states.sensor.car_time_until_departure.state|float }}"
    action:
      - service: switch.turn_on
        # CHANGE-ME: car heater power switch : DONE
        entity_id: switch.socket_1

  #------------automation

  - id: "car_heater_temp_sample_3h"
    alias: "CH: Sample temperature 3h before departure time"
    trigger:
      - platform: time_pattern
        minutes: "/1"
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ now().time().strftime("%H:%M") == states.sensor.car_heater_3h_before_start_time.state }}'
        - condition: state
          entity_id: input_boolean.car_heater_enable
          state: "on"
        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.car_heater_weekday
              state: "off"
            - condition: time
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.car_heater_3h_before_temp
          # CHANGE-ME: outside temperature sensor: DONE
          value: "{{ states('sensor.out_temperature') | float }}"
          # value: "{{ state_attr('weather.forecast_koti', 'temperature') | float }}"

  #------------automation

  - id: "car_heater_calculated_time"
    alias: "CH: Start engine heater at calculated start time"
    trigger:
      - platform: time_pattern
        minutes: "/1"
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ now().time().strftime("%H:%M") == states.sensor.car_heater_start_time.state }}'
        - condition: template
          value_template: "{{ states.sensor.car_heater_run_time.state|float > 0 }}"
        - condition: state
          entity_id: input_boolean.car_heater_enable
          state: "on"
        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.car_heater_weekday
              state: "off"
            - condition: time
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
    action:
      - service: switch.turn_on
        # CHANGE-ME: car heater power switch: DONE
        entity_id: switch.socket_1

  #------------automation

  - id: "car_heater_departure"
    alias: "CH: Stop engine heater at departure time"
    trigger:
      - platform: time_pattern
        minutes: "/1"
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ now().time().strftime("%H:%M:%S") == states.input_datetime.car_heater_departure_time.state }}'
        - condition: template
          value_template: "{{ states.sensor.car_heater_run_time.state|float > 0 }}"
        - condition: state
          entity_id: input_boolean.car_heater_enable
          state: "on"
        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.car_heater_weekday
              state: "off"
            - condition: time
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
    action:
      - service: switch.turn_off
        # CHANGE-ME: car heater power switch : DONE
        entity_id: switch.socket_1

#------------automation---

# Input sensors

input_datetime:
  car_heater_departure_time:
    name: Car heater departure time
    has_time: true
    has_date: false

input_number:
  car_heater_3h_before_temp:
    name: Sample temp
    unit_of_measurement: °C
    icon: mdi:thermometer
    min: -30
    max: 30
    step: 0.5

# Boolean sensors
input_boolean:
  car_heater_weekday:
    name: Only weekdays
    icon: mdi:calendar
  car_heater_enable:
    name: Enable car heating timer

sensor:
  - platform: template
    sensors:
      car_heater_run_time:
        friendly_name: "Calculated run time"
        unit_of_measurement: h
        value_template: >
          {% if ((states('input_number.car_heater_3h_before_temp')|float) < 10) %}
            {% if not states('input_number.car_heater_3h_before_temp') == 'unknown' %}
              {{(states('input_number.car_heater_3h_before_temp')|float * (-0.05) + 1)|round(1)}}
            {%endif%}
          {%else%}
            0
          {%endif%}

  - platform: template
    sensors:
      car_heater_3h_before_start_time:
        friendly_name: "3h before start time"
        icon_template: mdi:clock
        value_template: >
          {% if states.input_datetime.car_heater_departure_time.state is defined %}
              {{ strptime(((as_timestamp('1970-01-01 ' ~ states('input_datetime.car_heater_departure_time')) - (10800))|timestamp_custom), '%Y-%m-%d %H:%M:%S').strftime("%H:%M") }}
          {% else %}
              waiting for sensors
          {% endif%}
  - platform: template
    sensors:
      car_heater_start_time:
        friendly_name: "Calculated start time"
        icon_template: mdi:clock
        value_template: >
          {% if states.input_datetime.car_heater_departure_time.state is defined %}
            {% if ((states('sensor.car_heater_run_time')|float) > 0) %}
              {{ strptime(((as_timestamp('1970-01-01 ' ~ states('input_datetime.car_heater_departure_time')) - (states('sensor.car_heater_run_time')|float *3600))|timestamp_custom), '%Y-%m-%d %H:%M:%S').strftime("%H:%M") }}
            {%else%}
              Never
            {%endif%}
          {% else %}
              waiting for sensors
          {% endif%}
  - platform: template
    sensors:
      car_time_until_departure:
        friendly_name: "time until set departure"
        icon_template: mdi:clock
        value_template: '{{ (as_timestamp(now().strftime("%Y-%m-%d ") + states.input_datetime.car_heater_departure_time.state) - as_timestamp(now().strftime("%Y-%m-%d %H:%M"))) / 60 }}'
  - platform: template
    sensors:
      car_heater_status:
        friendly_name: "Car heater status"
        icon_template: mdi:clock
        # CHANGE-ME: car heater power switch (note: two entrys in this block)
        value_template: >
          {% if is_state('input_boolean.car_heater_enable', 'on') %}
            {% if is_state('switch.socket_1', 'on') %}
              Car heating is currently active and will be stopped at {{ states.input_datetime.car_heater_departure_time.state }}
            {% else %}
              Car heating will start approximately at {{ states.sensor.car_heater_start_time.state }} and will be stopped at {{ states.input_datetime.car_heater_departure_time.attributes.timestamp  | timestamp_custom("%H:%M", false) }}
            {% endif%}
          {% else %}
            {% if is_state('switch.socket_1', 'on') %}
              Car heating is active and controlled manually!
            {% else %}
              No car heating scheduled
            {%endif %}

          {% endif%}
  #------------sensors end ------------------------#
